let r = require,
    gulp = r('gulp'), 
    insert = r('gulp-insert-lite'),
    babel = r("gulp-babel"),
    merge = r('merge-stream');

let projects = [ CreateProject('src/**/*.js', 'dist/') ];

gulp.task('build', function() {
    return transpileAllProjects();
});

function CreateProject(sourceGLOB, destination) {
    return {
        source: sourceGLOB,
        destination: destination
    };
}

function transpileAllProjects() {
    
    let streams = [];
    
    for(let i in projects){
        let p = projects[i];
        let { source, destination } = p;
        console.log('Transpiling ' + source);
        let t = transpile(source, destination);        
        streams.push(t);
    }

    return merge(streams);
}

function transpile(source, output) {
    //prepends a comment to the babelified .js file so that developers know to look for the source version and make changes there
    let devNotice =
    `/* 
        NOTICE NOTICE NOTICE 
                         
        THIS IS AN AUTOMATICALLY GENERATED FILE BY GULP
        DO NOT EDIT THIS FILE DIRECTLY
        MAKE EDITS TO THE SAME FILE LOCATED IN THE 'SRC' FOLDER
    */`;

    return gulp.src(source)
    .pipe(babel({
        presets: ['@babel/env']
    }))
    .pipe(insert.prepend(devNotice))
    .pipe(gulp.dest(output))
}